// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCypbzQHdcifjARJqbjXNLrWakCac8rmls',
    appId: '1:958374770753:web:39693bc3b3c82b8fd06ec0',
    messagingSenderId: '958374770753',
    projectId: 'sugs-db6ac',
    authDomain: 'sugs-db6ac.firebaseapp.com',
    storageBucket: 'sugs-db6ac.firebasestorage.app',
    measurementId: 'G-ES6BSM3Z9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuAVeYqNbVoXwHq4zJYG8X-U2jEiOuf0',
    appId: '1:958374770753:android:916697cda77da32fd06ec0',
    messagingSenderId: '958374770753',
    projectId: 'sugs-db6ac',
    storageBucket: 'sugs-db6ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBStbITbMZyzw57DomDC1_3DuirhhmoHA8',
    appId: '1:958374770753:ios:f390ecfbdb2fdf60d06ec0',
    messagingSenderId: '958374770753',
    projectId: 'sugs-db6ac',
    storageBucket: 'sugs-db6ac.firebasestorage.app',
    iosBundleId: 'com.example.sugar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBStbITbMZyzw57DomDC1_3DuirhhmoHA8',
    appId: '1:958374770753:ios:f390ecfbdb2fdf60d06ec0',
    messagingSenderId: '958374770753',
    projectId: 'sugs-db6ac',
    storageBucket: 'sugs-db6ac.firebasestorage.app',
    iosBundleId: 'com.example.sugar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCypbzQHdcifjARJqbjXNLrWakCac8rmls',
    appId: '1:958374770753:web:5ce636fdd0619f1cd06ec0',
    messagingSenderId: '958374770753',
    projectId: 'sugs-db6ac',
    authDomain: 'sugs-db6ac.firebaseapp.com',
    storageBucket: 'sugs-db6ac.firebasestorage.app',
    measurementId: 'G-R9Q3QYBKD0',
  );
}
